name: mini_flutter_proyect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  cloud_firestore: 6.1.0
  firebase_database: 12.0.4
  image_picker: ^1.1.2
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^1.4.3
  location: ^8.0.1
  provider: ^6.1.5+1
  firebase_storage: ^13.0.4
  permission_handler: ^12.0.1
  flutter_image_compress: ^2.4.0
  path: ^1.9.0
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/locations - Copy (5).json
